### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Rame0ne** [hurdlegroup/robotjs#18]
## Expected Behavior
Just start it. So it should just work.

## Current Behavior
App threw an error during load
Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=119 uv=1 libc=glibc node=18.18.2 electron=28.3.0 webpack=true
    loaded from: ...\app

    at load.resolve.load.path (...\app\background.js:642:9)
    at load ...\app\background.js:604:30)
    at ./node_modules/@hurdlegroup/robotjs/index.js (...\app\background.js:20:98)
    at __webpack_require__ (...\app\background.js:22881:42)
    at ./main/ipcHandlers.ts (...\app\background.js:434:78)
    at __webpack_require__ (...\app\background.js:22881:42)
    at webpackUniversalModuleDefinition (...\app\background.js:3:20)

## Background.js
import { moveMouseSmooth } from "@hurdlegroup/robotjs";
moveMouseSmooth(pos.x, pos.y);

## Context
Make the Mouse move.

## Your Environment
* RobotJS version: latest
* Electron version: 28.3.0 
* Using Nextron
* Abi: 119
* Node.js version: 18.18.2
* npm version:
* Operating System: Win

**Comment by DanielMcAssey** [comment]
Im not sure on your build system, however we provide the following pre-built native builds
![image](https://github.com/hurdlegroup/robotjs/assets/3080979/7bb1b49a-c69f-49ee-9b52-58fe4f188039)

**Comment by dladeira** [comment]
Same issue here

```
Error: No native build was found for platform=linux arch=x64 runtime=electron abi=128 uv=1 libc=glibc node=20.17.0 electron=32.1.2
```

Could this have something to do with running it on electron? I'm using debian 12.

Also the link for the instructions in the README for electron is dead...

**Comment by DanielMcAssey** [comment]
@dladeira  Could you check that ./node_modules/@hurdlegroup/robotjs/prebuilds/

Includes the correct ".node" file for your platform please?

**Comment by dladeira** [comment]
@DanielMcAssey

This is the exact error that I'm getting

```
App threw an error during load
Error: No native build was found for platform=linux arch=x64 runtime=electron abi=128 uv=1 libc=glibc node=20.17.0 electron=32.1.2
    loaded from: [PATH]/dist-electron

    at l.resolve.l.path ([PATH]/dist-electron/main.js:1:1544)
    at l ([PATH]/dist-electron/main.js:1:885)
    at [PATH]/dist-electron/main.js:3:2102
    at Object.<anonymous> ([PATH]/dist-electron/main.js:3:2628)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at cjsLoader (node:internal/modules/esm/translators:350:17)
```


I ran `npm rebuild --runtime=electron --target=32.1.2 --disturl=https://atom.io/download/atom-shell --abi=128` (for electron version `32.1.2` abi `128` before this

This is how `./node_modules/@hurdlegroup/robotjs/prebuilds/` looks like for me

![image](https://github.com/user-attachments/assets/b747c627-440c-4208-b7e0-96a13940b194)

Linux x64 appears to be there, any ideas?

**Comment by DanielMcAssey** [comment]
You wont have to run npm rebuild as we package Node-API prebuilds.

We use it for electron, are you copying the ".node" files to the dist folder? What build system are you using? We use webpack

**Comment by dladeira** [comment]
What do you mean? For frontend I use Nuxt. I don't copy any files, just run it

**Comment by DanielMcAssey** [comment]
You will need to copy the .node addon files to the output directory, unfortunately I havent got experience with Nuxt, if not you will get the error you are getting.

**Comment by dladeira** [comment]
How would I go about finding this output directory? Nuxt is for frontend so it shouldn't have anything to do with the backend.

**Comment by DanielMcAssey** [comment]
Basically the ".node" files are Node Addon files, you want to copy them to the output directory.
How do you transpile your electron files?

**Comment by dladeira** [comment]
I'm not sure. I'm using the [nuxt-electron](https://nuxt.com/modules/electron) module. Nuxt originally uses Vite, but I'm pretty sure this module just runs the default electron configuration alongside Nuxt, and then loads the Nuxt window from electron.

This is how my directory looks like
![image](https://github.com/user-attachments/assets/7fa167fc-ef16-47f8-b5d2-6e2771a98d0f)

**Comment by DanielMcAssey** [comment]
You may need to mark this library as an external module, so it doesnt get bundled, "theoretically" it should copy it to output directory. But again im no expert in Vite or Nuxt

**Comment by dladeira** [comment]
> You may need to mark this library as an external module

Any idea how I would go about doing that?

**Comment by DanielMcAssey** [comment]
Having a quick look at: https://stackoverflow.com/questions/76352336/how-to-tell-vite-to-output-a-specified-file-into-a-specified-folder-with-rollupo

Look at the rollup options

**Comment by DanielMcAssey** [comment]
Additionally, I found this: https://github.com/vite-plugin/vite-plugin-native

**Comment by dladeira** [comment]
I found the fix. The rollup options indeed fixes it. I was trying to set it in the vite configuration normally in `nuxt.config.js` like so:

```
export default defineNuxtConfig({
  vite: {
    build: {
      rollupOptions: {
        external: ["@hurdlegroup/robotjs"],
      },
    },
  },
});
```



But turns out, [nuxt-electron](https://nuxt.com/modules/electron) uses [vite-plugin-electron](https://github.com/electron-vite/vite-plugin-electron) instead of Vite that Nuxt uses. I used this vite configuration there and it fixed the issue for me.

```
export default defineNuxtConfig({
  electron: {
    build: [
      {
        entry: "electron/main.ts",
        vite: {
          build: {
            rollupOptions: {
              external: ["@hurdlegroup/robotjs"],
            },
          },
        },
      },
      {
        entry: "electron/preload.ts",
        onstart(options) {
          // Notify the renderer process to reload the page when the preload-script is completely loaded
          // Instead of restarting the entire electron app
          options.reload();
        },
      },
    ],
    disableDefaultOptions: true,
  },
});
```

Thank you for the help @DanielMcAssey, forever grateful.
