### ISSUE TITLE
On Windows, keyTap always throws "Invalid key code specified"

### ISSUE THREAD

**Issue by johnlindquist** [hurdlegroup/robotjs#22]
I'm on node 20.11.1.

Everything is working great on Mac, but on Windows, even a simple:

```js
robot.keyTap("a") //throws "Error: Invalid key code specified"
```

```js
robot.keyTap("down") //throws "Error: Invalid key code specified"
```

I haven't been able to use keyTap at all on Windows (again, it's working fine on Mac).

Any ideas? Thanks so much!

**Comment by chuski1212** [comment]
Having the same issue :(

**Comment by mason-lane** [comment]
I'm on windows and was having this issue as well but came up with a workaround to use until this is fixed:
```
function tap (key) {
    robot.keyToggle(key, 'down');
    robot.keyToggle(key, 'up');
}

tap('escape');
```

`keyToggle` still worked fine for me, so I created a function that simulates a key tap by toggling a key down and then up. Then you can just call `tap` and pass in any compatible key string.

Hope this helps :)
